services:
  - type: web
    name: konntek-mdm-bot
    runtime: python
    pythonVersion: "3.12.4"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: ${{BOT_TOKEN}}
      - key: ADMIN_IDS
        value: ${{ADMIN_IDS}}
