services:
  - type: web
    name: konntek-mdm-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN_HERE
