services:
  - type: web
    name: konntek-mdm-bot
    runtime: python
    pythonVersion: "3.12.4"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: ${{BOT_TOKEN}}
      - key: BOT_PASSWORD
        value: ${{BOT_PASSWORD}}
      - key: ADMIN_IDS
        value: ${{ADMIN_IDS}}
      - key: DATA_PATH
        value: /opt/render/data  # Chemin de montage du disque persistant
      - key: DB_NAME
        value: /opt/render/data/mdm_bot.db  # Base de données dans le chemin persistant
    disks:
      - name: mdm-bot-data
        mountPath: /opt/render/data
        sizeGB: 50  # Taille du disque configurée à 50 Go
